name: Deploy Demo

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish Package"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install root dependencies
        run: yarn install --immutable

      - name: Update demo version
        run: yarn update-demo-version

      - name: Trigger Vercel deployment
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
