name: Deploy Demo to GitHub Pages

on:
  push:
    branches:
      - fix_demo_pages
    paths:
      - 'demo/**'
      - 'src/**'
      - '.github/workflows/deploy-demo.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install root dependencies
        run: yarn install --immutable

      - name: Build main package
        run: yarn build

      - name: Install demo dependencies
        run: |
          cd demo
          yarn install --immutable

      - name: Build demo
        run: |
          cd demo
          yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: demo/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
